### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by TitiMiti** [TitiMiti/GroupProjectTeamH#2]
Here will be a great story

**Comment by warferton** [comment]
reopen

**Comment by warferton** [comment]
Main User Story:

As a user I want the application to find and suggest me a gift, based on my preferences and any extra information I would specify. It should not take me long to get from opening the application to receiving my gift recommendations.  Also, if among the recommended products there would not be any that would satisfy my needs, I want the application to display a new set of recommendations by pressing one button("Refresh").  This should not take me back to specifying preferences but instantly display a new set of products based on the information I entered on my first try.

**Comment by TitiMiti** [comment]
🔥🔥🔥
