### ISSUE TITLE
File heirarchy and file naming. Important!.

### ISSUE THREAD

**Issue by warferton** [TitiMiti/GroupProjectTeamH#3]
Since it'll be a big project. I'd like to ask everyone to put their files and variables into according directories and var files.
E.g.,  if you have string variable for page 3 (let it be called "Selection"), store it in " values -> page_selection_strings.xml.
Identically store the .java file of the Selection activity in ui -> activities -> "SelectionPage" -> ... .  
And so on.

As for file and variable naming, it's pretty common thing, but still, try to name your var's and files as explicitly and easy to understand what they do and where do they belong as possible. (e.g., [Something])PageActivity, etc.)

Thank you.

**Comment by TitiMiti** [comment]
No prob
