### ISSUE TITLE
Useful Links

### ISSUE THREAD

**Issue by Zhuldyz20** [TitiMiti/GroupProjectTeamH#8]

**Comment by warferton** [comment]
eBay docs: 
auth grant flow - https://developer.ebay.com/api-docs/static/oauth-authorization-code-grant.html
sandbox - https://developer.ebay.com/DevZone/build-test/test-tool/?index=0&api=catalog&call=product_summary_search__GET&variation=json
catalog API Doc - https://developer.ebay.com/api-docs/commerce/catalog/resources/methods

**Comment by CarlosAvila185** [comment]
https://github.com/eBay/ebay-oauth-java-client#installation - installation and other things for the API.

**Comment by warferton** [comment]
Android OAuth 2.0 - https://github.com/eBay/ebay-oauth-android-client

**Comment by Zhuldyz20** [comment]
making a call - https://developer.ebay.com/DevZone/merchandising/docs/Concepts/MerchandisingAPI_FormatOverview.html
retrieving items - https://developer.ebay.com/DevZone/guides/features-guide/content/development/Items-Retrieving.html

**Comment by Zhuldyz20** [comment]
getSellerList call - https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/GetSellerList.html (цу need to use seller's token and specify CategoryID for making this call)
getStore API call to get the CategoryID by using seller's token - https://developer.ebay.com/Devzone/XML/docs/Reference/eBay/GetStore.html

**Comment by warferton** [comment]
https://developer.ebay.com/api-docs/static/oauth-auth-code-grant-request.html --my last stop

**Comment by CarlosAvila185** [comment]
Alex, this is where I got the "Volley" class if you want to read more about it: https://developer.android.com/training/volley/simple

**Comment by CarlosAvila185** [comment]
> https://developer.ebay.com/api-docs/static/oauth-auth-code-grant-request.html --my last stop

This is also where I stopped, I had to "implement" volley to see if the http request worked.

**Comment by CarlosAvila185** [comment]
I think we should close this issue since we are not using ebay anymore.🤗

**Comment by warferton** [comment]
aye aye
